#!/usr/bin/env node
/**
 * gen-sitemap.mjs — build-time sitemap generator.
 *
 * Apex sitemap.xml = hub URLs only (cross-host mega-sitemap removed — re-audit §3.6).
 * Island hosts get per-host sitemaps via sitemap-index + _sitemaps/.
 * Oʻahu EN↔JA pairs get xhtml:link hreflang annotations.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const SITES_DIR = join(ROOT, 'src/sites');
const PUBLIC = join(ROOT, 'public');
const SITE_URL = 'https://mychef-hawaii.com';
const LASTMOD = new Date().toISOString().slice(0, 10);

const BASE = { hub: '', oahu: '/oahu', maui: '/maui', kauai: '/kauai', bigisland: '/bigisland' };

const OAHU_JA_PAIRS = new Map([
  ['/', '/ja'],
  ['/ja', '/'],
  ['/ja/omakase-at-home', '/omakase-at-home'],
  ['/omakase-at-home', '/ja/omakase-at-home'],
  ['/ja/waikiki-private-chef', '/waikiki-private-chef'],
  ['/waikiki-private-chef', '/ja/waikiki-private-chef'],
  ['/ja/stay-chef', '/stay-chef'],
  ['/stay-chef', '/ja/stay-chef'],
  ['/ja/weddings', '/weddings'],
  ['/weddings', '/ja/weddings'],
]);

function locFor(siteId, path) {
  if (siteId === 'hub') return `${SITE_URL}${path === '/' ? '/' : path}`;
  const rest = path.replace(new RegExp(`^/${siteId}`), '') || '/';
  return `https://${siteId}.mychef-hawaii.com${rest === '/' ? '/' : rest}`;
}

function pathOnHost(loc) {
  try {
    const u = new URL(loc);
    return u.pathname.replace(/\/$/, '') || '/';
  } catch {
    return '/';
  }
}

function urlXml(loc, priority, siteId) {
  let xhtml = '';
  if (siteId === 'oahu') {
    const p = pathOnHost(loc);
    const twin = OAHU_JA_PAIRS.get(p);
    if (twin) {
      const isJa = p === '/ja' || p.startsWith('/ja/');
      const enPath = isJa ? (p.replace(/^\/ja/, '') || '/') : p;
      const jaPath = isJa ? p : enPath === '/' ? '/ja' : `/ja${enPath}`;
      const enHref = locFor('oahu', enPath === '/' ? '/oahu' : `/oahu${enPath}`);
      const jaHref = locFor('oahu', jaPath === '/' ? '/oahu/ja' : `/oahu${jaPath}`);
      xhtml = `
    <xhtml:link rel="alternate" hreflang="en" href="${enHref}" />
    <xhtml:link rel="alternate" hreflang="ja" href="${jaHref}" />
    <xhtml:link rel="alternate" hreflang="x-default" href="${enHref}" />`;
    }
  }
  return `  <url>
    <loc>${loc}</loc>
    <lastmod>${LASTMOD}</lastmod>
    <priority>${priority}</priority>${xhtml}
  </url>`;
}

const bySite = { hub: [], oahu: [], maui: [], kauai: [], bigisland: [] };

for (const siteId of readdirSync(SITES_DIR)) {
  const base = BASE[siteId];
  if (base === undefined) continue;
  const file = join(SITES_DIR, siteId, 'content.ts');
  const slugs = new Set(['', 'quote']);
  if (siteId === 'hub') slugs.add('calculator');
  if (existsSync(file)) {
    const src = readFileSync(file, 'utf8');
    for (const m of src.matchAll(/slug:\s*'([^']*)'/g)) slugs.add(m[1]);
  }
  for (const slug of slugs) {
    const path = `${base}/${slug}`.replace(/\/$/, '') || '/';
    const priority = path === '/' ? '1.0' : slug === '' ? '0.9' : slug === 'pricing' ? '0.9' : '0.7';
    const loc = locFor(siteId, path);
    bySite[siteId].push({ loc, priority, siteId });
  }
}

const xmlns =
  'xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml"';

// Apex sitemap.xml = hub only (no cross-host entries)
const hubBody = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/gen-sitemap.mjs — hub URLs only. -->
<urlset ${xmlns}>
${bySite.hub
  .sort((a, b) => a.loc.localeCompare(b.loc))
  .map((u) => urlXml(u.loc, u.priority, 'hub'))
  .join('\n')}
</urlset>
`;
writeFileSync(join(PUBLIC, 'sitemap.xml'), hubBody);
writeFileSync(join(PUBLIC, 'sitemap-hub.xml'), hubBody);

const indexEntries = [`  <sitemap>
    <loc>${SITE_URL}/sitemap-hub.xml</loc>
    <lastmod>${LASTMOD}</lastmod>
  </sitemap>`];

for (const siteId of ['oahu', 'maui', 'kauai', 'bigisland']) {
  const name = `sitemap-${siteId}.xml`;
  const hostBase = `https://${siteId}.mychef-hawaii.com`;
  const body = `<?xml version="1.0" encoding="UTF-8"?>
<urlset ${xmlns}>
${bySite[siteId]
  .sort((a, b) => a.loc.localeCompare(b.loc))
  .map((u) => urlXml(u.loc, u.priority, siteId))
  .join('\n')}
</urlset>
`;
  writeFileSync(join(PUBLIC, name), body);
  indexEntries.push(`  <sitemap>
    <loc>${hostBase}/sitemap.xml</loc>
    <lastmod>${LASTMOD}</lastmod>
  </sitemap>`);
  mkdirSync(join(PUBLIC, '_sitemaps'), { recursive: true });
  writeFileSync(join(PUBLIC, '_sitemaps', `${siteId}.xml`), body);
}

writeFileSync(
  join(PUBLIC, 'sitemap-index.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${indexEntries.join('\n')}
</sitemapindex>
`,
);

console.log(
  `sitemap.xml: ${bySite.hub.length} hub URLs · islands ${['oahu', 'maui', 'kauai', 'bigisland'].map((s) => bySite[s].length).join('/')} · lastmod ${LASTMOD}`,
);
