#!/usr/bin/env node
/**
 * gen-sitemap.mjs — build-time sitemap generator.
 *
 * Hub URLs stay on the apex. Island URLs emit on flagship subdomains
 * (canonical architecture after 2026-09-09 audit Phase 3).
 * Also writes per-island sitemaps + a sitemap index.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const SITES_DIR = join(ROOT, 'src/sites');
const PUBLIC = join(ROOT, 'public');
const SITE_URL = 'https://mychef-hawaii.com';
const LASTMOD = new Date().toISOString().slice(0, 10);

const BASE = { hub: '', oahu: '/oahu', maui: '/maui', kauai: '/kauai', bigisland: '/bigisland' };

function locFor(siteId, path) {
  if (siteId === 'hub') return `${SITE_URL}${path === '/' ? '/' : path}`;
  const rest = path.replace(new RegExp(`^/${siteId}`), '') || '/';
  return `https://${siteId}.mychef-hawaii.com${rest === '/' ? '/' : rest}`;
}

function urlXml(loc, priority) {
  return `  <url>
    <loc>${loc}</loc>
    <lastmod>${LASTMOD}</lastmod>
    <priority>${priority}</priority>
  </url>`;
}

const bySite = { hub: [], oahu: [], maui: [], kauai: [], bigisland: [] };

for (const siteId of readdirSync(SITES_DIR)) {
  const base = BASE[siteId];
  if (base === undefined) continue;
  const file = join(SITES_DIR, siteId, 'content.ts');
  const slugs = new Set(['', 'quote']);
  if (siteId === 'hub') slugs.add('calculator');
  if (existsSync(file)) {
    const src = readFileSync(file, 'utf8');
    for (const m of src.matchAll(/slug:\s*'([^']*)'/g)) slugs.add(m[1]);
  }
  for (const slug of slugs) {
    const path = `${base}/${slug}`.replace(/\/$/, '') || '/';
    const priority = path === '/' ? '1.0' : slug === '' ? '0.9' : slug === 'pricing' ? '0.9' : '0.7';
    const loc = locFor(siteId, path);
    bySite[siteId].push({ loc, priority });
  }
}

const all = Object.values(bySite).flat().sort((a, b) => a.loc.localeCompare(b.loc));

const master = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/gen-sitemap.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${all.map((u) => urlXml(u.loc, u.priority)).join('\n')}
</urlset>
`;
writeFileSync(join(PUBLIC, 'sitemap.xml'), master);

const indexEntries = [`  <sitemap>
    <loc>${SITE_URL}/sitemap-hub.xml</loc>
    <lastmod>${LASTMOD}</lastmod>
  </sitemap>`];

for (const siteId of ['hub', 'oahu', 'maui', 'kauai', 'bigisland']) {
  const name = siteId === 'hub' ? 'sitemap-hub.xml' : `sitemap-${siteId}.xml`;
  const hostBase = siteId === 'hub' ? SITE_URL : `https://${siteId}.mychef-hawaii.com`;
  const body = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${bySite[siteId]
  .sort((a, b) => a.loc.localeCompare(b.loc))
  .map((u) => urlXml(u.loc, u.priority))
  .join('\n')}
</urlset>
`;
  writeFileSync(join(PUBLIC, name), body);
  if (siteId !== 'hub') {
    indexEntries.push(`  <sitemap>
    <loc>${hostBase}/sitemap.xml</loc>
    <lastmod>${LASTMOD}</lastmod>
  </sitemap>`);
    // Island hosts also need a sitemap.xml copy at public/ for rewrite — write under public/islands/
    mkdirSync(join(PUBLIC, '_sitemaps'), { recursive: true });
    writeFileSync(join(PUBLIC, '_sitemaps', `${siteId}.xml`), body);
  }
}

writeFileSync(
  join(PUBLIC, 'sitemap-index.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${indexEntries.join('\n')}
</sitemapindex>
`,
);

console.log(`sitemap.xml: ${all.length} URLs (subdomain-canonical islands) · lastmod ${LASTMOD}`);
