#!/usr/bin/env node
/**
 * gen-sitemap.mjs — build-time sitemap generator.
 *
 * Reads every src/sites/<site>/content.ts registry, extracts the `slug: '...'`
 * entries (the ContentRecord contract), and emits public/sitemap.xml.
 * Island agents only need to fill their content.ts — their URLs append
 * automatically on the next build. Bespoke routes that must exist even with
 * an empty registry ('' home, 'quote') are added per site by default.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const SITES_DIR = join(ROOT, 'src/sites');
const OUT = join(ROOT, 'public/sitemap.xml');
const SITE_URL = 'https://mychef-hawaii.com';

/** site id → base path ('' for the hub) */
const BASE = { hub: '', oahu: '/oahu', maui: '/maui', kauai: '/kauai', bigisland: '/bigisland' };

const urls = [];

for (const siteId of readdirSync(SITES_DIR)) {
  const base = BASE[siteId];
  if (base === undefined) continue;
  const file = join(SITES_DIR, siteId, 'content.ts');
  const slugs = new Set(['', 'quote']); // bespoke routes always present
  if (existsSync(file)) {
    const src = readFileSync(file, 'utf8');
    for (const m of src.matchAll(/slug:\s*'([^']*)'/g)) slugs.add(m[1]);
  }
  for (const slug of slugs) {
    const path = `${base}/${slug}`.replace(/\/$/, '') || '/';
    const priority = path === '/' ? '1.0' : slug === '' ? '0.9' : slug === 'pricing' ? '0.9' : '0.7';
    urls.push({ loc: `${SITE_URL}${path}`, priority });
  }
}

urls.sort((a, b) => a.loc.localeCompare(b.loc));

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/gen-sitemap.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    (u) => `  <url>
    <loc>${u.loc}</loc>
    <priority>${u.priority}</priority>
  </url>`,
  )
  .join('\n')}
</urlset>
`;

writeFileSync(OUT, xml);
console.log(`sitemap.xml: ${urls.length} URLs`);
